### ISSUE TITLE
cleanup ExShell from gamedir

### ISSUE THREAD

**Issue by tais** [1dot13/gamedir#2]
it seems ExShell might be unusable, abandoned and could possibly be removed

**Comment by Asdow** [comment]
I agree. IIRC it was used to do xbrz scaling on the cpu for JA but nowadays that can be done on the gpu with ReShade and a pixel shader so long as the ddraw wrapper is updated to one that uses either OpenGL, DX9-12 or Vulkan.

**Comment by kitty624** [comment]
honestly, i don't get the use of the whole folder "tools". those are very specific tools that, for whatever reason, are not stored at https://storage.rcs-rds.ro/links/4729f8d6-f44b-42b7-aa3e-e0ddc6deead6?path=%2FJA_2%2FModding_Tools (there are older versions of the FaceViewer). Couldn't we get a hold on to whoever has rights to upload there (Hawkeye?) and add them there and put a link to tools-download into "docs" instead? I mean, the FacViewer is needed, but why is it more important than other tools there? so, if not needed for anything upcoming, why not remove the whole folder?

**Comment by Asdow** [comment]
Another option would be to expand it and include tools that are most useful to a modder from the rds.ro storage and add them to Tools under gamedir. That way no one who wants to start modding would have to hunt down for the tools from different places.

I've no knowledge on the modding tools though, so we'd need someone who's used them and knows which ones would actually be useful, if we were inclined to do so
