### ISSUE TITLE
Change certain options default setting

### ISSUE THREAD

**Issue by Asdow** [1dot13/gamedir#21]
When downloading a release, I noticed that showing trees and smart tree tops are off by default. Imo, it would make sense to turn both options on, as the smart tree tops setting practically eliminates the need to ever have to manually turn tree tops on or off during gameplay.

Ditto for auto fast forward for AI turns. It should only affect AI that is not currently visible and who likes having longer turns?

And possibly lobot as well? Anyone who prefers new sprites can disable the option, but for new players who might not know about it, it'd be on by default

**Comment by NorthFury** [comment]
I completely agree with you. We should change the default options to what we consider to be the recommended settings for someone to be playing 1.13.
Fast AI turns and auto tree tops is easy to infer what it is, but there are things like lobot where users don't know what it is about.

**Comment by NorthFury** [comment]
I completely agree with you. We should change the default options to what we consider to be the recommended settings for someone to be playing 1.13.
Fast AI turns and auto tree tops is easy to infer what it is, but there are things like lobot where users don't know what it is about.

**Comment by Asdow** [comment]
Yeah, that option could be renamed to something more explicit. Lobot/logical bodytypes is an ok term for dev team to refer to the feature but it doesn't properly convey what it actually does as an ingame option text

**Comment by Asdow** [comment]
Strictly in-game options for now, these would be my proposed changes

Show Movement Path -> True
Sleep/Wake Notifications -> False
Show Tree Tops -> True
Smart Tree Tops -> True
High-Angle Grenade Launching -> True
Tracer Effect for Single Shot -> True
Logical Bodytypes -> True
Auto Fast Forward AI Turns -> True
Start at maximum aim -> True
