### ISSUE TITLE
Can't start JA2

### ISSUE THREAD

**Issue by derissbread** [1dot13/gamedir#43]
File     :  ..\ext\VFS\src\Core\vfs_init.cpp
Line     :  286
Location :  vfs_init::initVirtualFileSystem

   Could not initialize library [ Data\Ambient.slf ] in : profile [ SLF Libs ], path [ Data\Ambient.slf ]

**Comment by Asdow** [comment]
You need original game data files, in addition to 1.13 data and executable files

**Comment by derissbread** [comment]
Does the game source file mean JA2 GOLD 1.12?

**Comment by Asdow** [comment]
Yes
