### ISSUE TITLE
Just a doubt

### ISSUE THREAD

**Issue by MarcusOSG** [1dot13/gamedir#98]
I updated the latest version (about 13 hours ago at the time of this comment), the game is working normally, my save, etc. But in the game information (ex: when we open the game in the upper left corner it says GitHub...... etc) it shows that the version it's from the previous month (October), Am I actually using the new patch or last month's patch? 

I just downloaded the update hours ago, extracted it, put all the files inside at the game directory, Do I have to do something else or something?

**Comment by Asdow** [comment]
No, it's correct and you don't have to do anything else. The changes to this repository with the game files does not affect the versioning ingame, which is for source code changes.

**Comment by MarcusOSG** [comment]
> No, it's correct and you don't have to do anything else. The changes to this repository with the game files does not affect the versioning ingame, which is for source code changes.

Oh okay, thank you for the attention, u guys do a great jobs :)
